# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  upload_to_codecov:
    docker:
      - image: circleci/ruby:2.7  # Use an appropriate Docker image for your project
    steps:
      - checkout  # This pulls down your source code
      - run:
          name: Install Specific Bundler Version
          command: gem install bundler -v 2.4.22
      - run:
          name: Install Gems
          command: bundle install
      - run:
          name: Run Slather
          command: |
            bundle exec slather coverage --scheme PurLog PurLog.xcodeproj
            bash <(curl -s https://codecov.io/bash) -f test_report/cobertura.xml -X coveragepy -X gcov -X xcode
      - codecov/upload  # Upload the coverage report to Codecov

workflows:
  upload-to-codecov:
    jobs:
      - upload_to_codecov
