# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  macos: circleci/macos@2
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    macos:
      xcode: "15.4.0" # Specify the Xcode version you are using
    environment:
      # Define any environment variables you might need
      XCODE_SCHEME: "PurLog"
      XCODE_PROJECT: "PurLog.xcodeproj"
      XCODE_SDK: "iphonesimulator"
      XCODE_DESTINATION: "platform=iOS Simulator,OS=17.5,name=iPhone 15"
    steps:
      - checkout

      - run:
          name: Install Gems
          command: |
            gem install bundler
            bundle install

      - run:
          name: Build and Test
          command: |
            xcodebuild clean test \
              -project "$XCODE_PROJECT" \
              -scheme "$XCODE_SCHEME" \
              -sdk "$XCODE_SDK" \
              -destination "$XCODE_DESTINATION" \
              -enableCodeCoverage YES | xcpretty --test --color

      - run:
          name: Run Slather Coverage
          command: |
            bundle exec slather coverage --scheme "$XCODE_SCHEME" "$XCODE_PROJECT"
      - run:
          name: Codecov Upload
          command: |
            bash <(curl -s https://codecov.io/bash) -f test_report/cobertura.xml -X coveragepy -X gcov -X xcode -t $CODECOV_TOKEN

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-test
