# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1
  macos: circleci/macos@2

jobs:
  upload_to_codecov:
    macos:
      xcode: "15.4.0"  # Choose the Xcode version that fits your needs
    steps:
      - macos/preboot-simulator:
          version: "17.5"
          platform: "iOS"
          device: "iPhone 15"
      - checkout  # This pulls down your source code
      - run:
          name: Install Bundler
          command: gem install bundler -v 2.4.22
      - run:
          name: Install Gems
          command: bundle install
      - run:
          name: Clean
          command: xcodebuild clean -project PurLog.xcodeproj -scheme PurLog
      - run:
          name: Build and Test
          command: |
            xcodebuild test \
            -project PurLog.xcodeproj \
            -scheme PurLog \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            -enableCodeCoverage YES
      - run:
          name: Run Slather
          command: |
            bundle exec slather coverage --configuration Debug --scheme PurLog PurLog.xcodeproj
            bash <(curl -s https://codecov.io/bash) -f test_report/cobertura.xml -X coveragepy -X gcov -X xcode
      - codecov/upload  # Upload the coverage report to Codecov

workflows:
  upload-to-codecov:
    jobs:
      - upload_to_codecov
