# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  macos: circleci/macos@2

jobs:
  build-and-test:
    macos:
      xcode: "14.3.0" # Specify the Xcode version you are using
    environment:
      # Define any environment variables you might need
      XCODE_SCHEME: "PurLog"
      XCODE_PROJECT: "PurLog.xcodeproj"
      XCODE_SDK: "iphonesimulator"
      XCODE_DESTINATION: "platform=iOS Simulator,OS=16.4,name=iPhone 14"
    steps:
      - checkout

      - run:
          name: Install Gems
          command: |
            gem install bundler
            bundle install

      - run:
          name: Build and Test
          command: |
            xcodebuild clean test \
              -project "$XCODE_PROJECT" \
              -scheme "$XCODE_SCHEME" \
              -sdk "$XCODE_SDK" \
              -destination "$XCODE_DESTINATION" \
              -enableCodeCoverage YES | xcpretty --test --color

      - store_artifacts:
          path: ~/Library/Developer/Xcode/DerivedData
          destination: derived_data

      - store_test_results:
          path: ~/Library/Developer/Xcode/DerivedData

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-test
